"""empty message

Revision ID: 10be97436859
Revises: 1c806f1c9669
Create Date: 2022-07-30 17:33:20.153934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10be97436859'
down_revision = '1c806f1c9669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('status', sa.String(length=255), default="active"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'status')
    # ### end Alembic commands ###
