"""empty message

Revision ID: 1c806f1c9669
Revises: 0a90354a883f
Create Date: 2022-07-18 16:43:34.977349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c806f1c9669'
down_revision = '0a90354a883f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('guesses', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'guesses')
    # ### end Alembic commands ###
