"""empty message

Revision ID: ac284300a1ef
Revises: 10be97436859
Create Date: 2022-07-31 16:13:57.467826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac284300a1ef'
down_revision = '10be97436859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('mode', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'mode')
    # ### end Alembic commands ###
